-- ============================================================
-- ProgramLab: exercise_library — seeded from the Training Program
-- Library workbook ('Exercise Library' sheet). Coach can add/remove;
-- clients can read. Re-runnable (on conflict do nothing).
-- Run in Supabase dashboard → SQL Editor → New query.
-- ============================================================

create table if not exists public.exercise_library (
  id         uuid primary key default gen_random_uuid(),
  category   text not null,
  pattern    text not null,
  equipment  text not null,
  name       text not null,
  created_at timestamptz not null default now(),
  unique (category, pattern, equipment, name)
);

alter table public.exercise_library enable row level security;
drop policy if exists library_coach  on public.exercise_library;
drop policy if exists library_read   on public.exercise_library;
create policy library_coach on public.exercise_library for all to authenticated
  using (public.is_coach()) with check (public.is_coach());
create policy library_read on public.exercise_library for select to authenticated
  using (true);

insert into public.exercise_library (category, pattern, equipment, name) values
  ('LOWER BODY', 'Squat (knee)', 'Default', 'Back Squat'),
  ('LOWER BODY', 'Squat (knee)', 'Barbell', 'Back / Front Squat'),
  ('LOWER BODY', 'Squat (knee)', 'Dumbbell', 'DB Goblet / Front Squat'),
  ('LOWER BODY', 'Squat (knee)', 'Machine / Cable', 'Hack / Leg Press'),
  ('LOWER BODY', 'Squat (knee)', 'Band', 'Band Squat (over shoulders)'),
  ('LOWER BODY', 'Squat (knee)', 'Bodyweight', 'Box / Bodyweight Squat'),
  ('LOWER BODY', 'Squat (knee)', 'Kettlebell', 'KB Goblet Squat'),
  ('LOWER BODY', 'Hinge (hip)', 'Default', 'Romanian Deadlift'),
  ('LOWER BODY', 'Hinge (hip)', 'Barbell', 'Deadlift / RDL'),
  ('LOWER BODY', 'Hinge (hip)', 'Dumbbell', 'DB RDL / Suitcase DL'),
  ('LOWER BODY', 'Hinge (hip)', 'Machine / Cable', 'Cable Pull-Through / 45° Back Ext'),
  ('LOWER BODY', 'Hinge (hip)', 'Band', 'Band Pull-Through / Good Morning'),
  ('LOWER BODY', 'Hinge (hip)', 'Bodyweight', 'Single-Leg Hip Hinge'),
  ('LOWER BODY', 'Hinge (hip)', 'Kettlebell', 'KB Deadlift / Swing'),
  ('LOWER BODY', 'Lunge / Single-Leg', 'Default', 'Reverse Lunge'),
  ('LOWER BODY', 'Lunge / Single-Leg', 'Barbell', 'BB Reverse Lunge / Split Squat'),
  ('LOWER BODY', 'Lunge / Single-Leg', 'Dumbbell', 'DB Walking / Reverse Lunge'),
  ('LOWER BODY', 'Lunge / Single-Leg', 'Machine / Cable', 'Smith Split Squat / Leg Press (1-leg)'),
  ('LOWER BODY', 'Lunge / Single-Leg', 'Band', 'Band Split Squat'),
  ('LOWER BODY', 'Lunge / Single-Leg', 'Bodyweight', 'Bodyweight Lunge / Step-Up'),
  ('LOWER BODY', 'Lunge / Single-Leg', 'Kettlebell', 'KB Front-Rack Lunge'),
  ('LOWER BODY', 'Posterior / Glute', 'Default', 'Hip Thrust'),
  ('LOWER BODY', 'Posterior / Glute', 'Barbell', 'BB Hip Thrust'),
  ('LOWER BODY', 'Posterior / Glute', 'Dumbbell', 'DB Hip Thrust / Glute Bridge'),
  ('LOWER BODY', 'Posterior / Glute', 'Machine / Cable', 'Cable Kickback / Glute Machine'),
  ('LOWER BODY', 'Posterior / Glute', 'Band', 'Band Glute Bridge / Monster Walk'),
  ('LOWER BODY', 'Posterior / Glute', 'Bodyweight', 'Single-Leg Glute Bridge'),
  ('LOWER BODY', 'Posterior / Glute', 'Kettlebell', 'KB Swing / Bridge'),
  ('LOWER BODY', 'Quad isolation', 'Default', 'Leg Extension'),
  ('LOWER BODY', 'Quad isolation', 'Dumbbell', 'DB Step-Up (slow)'),
  ('LOWER BODY', 'Quad isolation', 'Machine / Cable', 'Leg Extension'),
  ('LOWER BODY', 'Quad isolation', 'Band', 'Band Leg Extension'),
  ('LOWER BODY', 'Quad isolation', 'Bodyweight', 'Wall Sit / Sissy Squat'),
  ('LOWER BODY', 'Quad isolation', 'Kettlebell', 'KB Goblet Wall Sit'),
  ('LOWER BODY', 'Hamstring (knee-flex)', 'Default', 'Leg Curl'),
  ('LOWER BODY', 'Hamstring (knee-flex)', 'Dumbbell', 'DB / Nordic Curl'),
  ('LOWER BODY', 'Hamstring (knee-flex)', 'Machine / Cable', 'Lying / Seated Leg Curl'),
  ('LOWER BODY', 'Hamstring (knee-flex)', 'Band', 'Band Leg Curl'),
  ('LOWER BODY', 'Hamstring (knee-flex)', 'Bodyweight', 'Nordic / Slider Curl'),
  ('LOWER BODY', 'Hamstring (knee-flex)', 'Kettlebell', 'KB Swing (assist)'),
  ('LOWER BODY', 'Calf / Lower leg', 'Default', 'Standing Calf Raise'),
  ('LOWER BODY', 'Calf / Lower leg', 'Barbell', 'BB Calf Raise'),
  ('LOWER BODY', 'Calf / Lower leg', 'Dumbbell', 'DB Single-Leg Calf Raise'),
  ('LOWER BODY', 'Calf / Lower leg', 'Machine / Cable', 'Calf Machine / Leg Press Calf'),
  ('LOWER BODY', 'Calf / Lower leg', 'Band', 'Band Calf Press'),
  ('LOWER BODY', 'Calf / Lower leg', 'Bodyweight', 'Step Calf Raise'),
  ('LOWER BODY', 'Calf / Lower leg', 'Kettlebell', 'KB Goblet Calf Raise'),
  ('UPPER BODY — PUSH', 'Horizontal Push', 'Default', 'Bench Press'),
  ('UPPER BODY — PUSH', 'Horizontal Push', 'Barbell', 'Barbell Bench / Floor Press'),
  ('UPPER BODY — PUSH', 'Horizontal Push', 'Dumbbell', 'DB Bench / Floor Press'),
  ('UPPER BODY — PUSH', 'Horizontal Push', 'Machine / Cable', 'Chest Press / Cable Press'),
  ('UPPER BODY — PUSH', 'Horizontal Push', 'Band', 'Band Chest Press'),
  ('UPPER BODY — PUSH', 'Horizontal Push', 'Bodyweight', 'Push-Up (incl. deficit)'),
  ('UPPER BODY — PUSH', 'Horizontal Push', 'Kettlebell', 'KB Floor Press'),
  ('UPPER BODY — PUSH', 'Incline Push', 'Default', 'Incline DB Press'),
  ('UPPER BODY — PUSH', 'Incline Push', 'Barbell', 'Incline Barbell Press'),
  ('UPPER BODY — PUSH', 'Incline Push', 'Dumbbell', 'Incline DB Press'),
  ('UPPER BODY — PUSH', 'Incline Push', 'Machine / Cable', 'Incline Machine / High Cable'),
  ('UPPER BODY — PUSH', 'Incline Push', 'Band', 'Band Low-to-High Press'),
  ('UPPER BODY — PUSH', 'Incline Push', 'Bodyweight', 'Decline (feet-up) Push-Up'),
  ('UPPER BODY — PUSH', 'Incline Push', 'Kettlebell', 'KB Incline Press'),
  ('UPPER BODY — PUSH', 'Vertical Push', 'Default', 'Overhead Press'),
  ('UPPER BODY — PUSH', 'Vertical Push', 'Barbell', 'BB Strict / Push Press'),
  ('UPPER BODY — PUSH', 'Vertical Push', 'Dumbbell', 'DB Shoulder Press'),
  ('UPPER BODY — PUSH', 'Vertical Push', 'Machine / Cable', 'Shoulder Press Machine'),
  ('UPPER BODY — PUSH', 'Vertical Push', 'Band', 'Band Overhead Press'),
  ('UPPER BODY — PUSH', 'Vertical Push', 'Bodyweight', 'Pike / HSPU Progression'),
  ('UPPER BODY — PUSH', 'Vertical Push', 'Kettlebell', 'KB Strict / Push Press'),
  ('UPPER BODY — PUSH', 'Triceps', 'Default', 'Cable Pressdown'),
  ('UPPER BODY — PUSH', 'Triceps', 'Barbell', 'BB Skullcrusher / CGBP'),
  ('UPPER BODY — PUSH', 'Triceps', 'Dumbbell', 'DB Overhead Ext / Kickback'),
  ('UPPER BODY — PUSH', 'Triceps', 'Machine / Cable', 'Cable Pressdown / Dip Machine'),
  ('UPPER BODY — PUSH', 'Triceps', 'Band', 'Band Pressdown'),
  ('UPPER BODY — PUSH', 'Triceps', 'Bodyweight', 'Bench / Bar Dip · Diamond Push-Up'),
  ('UPPER BODY — PUSH', 'Triceps', 'Kettlebell', 'KB Overhead Extension'),
  ('UPPER BODY — PULL', 'Vertical Pull', 'Default', 'Pull-Up'),
  ('UPPER BODY — PULL', 'Vertical Pull', 'Dumbbell', 'DB Pullover'),
  ('UPPER BODY — PULL', 'Vertical Pull', 'Machine / Cable', 'Lat Pulldown'),
  ('UPPER BODY — PULL', 'Vertical Pull', 'Band', 'Band Lat Pulldown / Assisted Pull-Up'),
  ('UPPER BODY — PULL', 'Vertical Pull', 'Bodyweight', 'Pull-Up / Inverted (feet high)'),
  ('UPPER BODY — PULL', 'Vertical Pull', 'Kettlebell', 'KB Pullover'),
  ('UPPER BODY — PULL', 'Horizontal Pull', 'Default', 'Bent-Over Row'),
  ('UPPER BODY — PULL', 'Horizontal Pull', 'Barbell', 'BB Bent / Pendlay Row'),
  ('UPPER BODY — PULL', 'Horizontal Pull', 'Dumbbell', 'DB 1-Arm / Chest-Supported Row'),
  ('UPPER BODY — PULL', 'Horizontal Pull', 'Machine / Cable', 'Seated Cable / Machine Row'),
  ('UPPER BODY — PULL', 'Horizontal Pull', 'Band', 'Band Seated Row'),
  ('UPPER BODY — PULL', 'Horizontal Pull', 'Bodyweight', 'Inverted Row / Table Row'),
  ('UPPER BODY — PULL', 'Horizontal Pull', 'Kettlebell', 'KB 1-Arm Row'),
  ('UPPER BODY — PULL', 'Rear Delt / Upper Back', 'Default', 'Face Pull'),
  ('UPPER BODY — PULL', 'Rear Delt / Upper Back', 'Barbell', 'BB High Row'),
  ('UPPER BODY — PULL', 'Rear Delt / Upper Back', 'Dumbbell', 'DB Rear-Delt Fly / Y-Raise'),
  ('UPPER BODY — PULL', 'Rear Delt / Upper Back', 'Machine / Cable', 'Cable Face Pull / Reverse Pec-Deck'),
  ('UPPER BODY — PULL', 'Rear Delt / Upper Back', 'Band', 'Band Face Pull / Pull-Apart'),
  ('UPPER BODY — PULL', 'Rear Delt / Upper Back', 'Bodyweight', 'Prone Y-T-W Raise'),
  ('UPPER BODY — PULL', 'Rear Delt / Upper Back', 'Kettlebell', 'KB Rear-Delt Row'),
  ('UPPER BODY — PULL', 'Biceps', 'Default', 'DB Curl'),
  ('UPPER BODY — PULL', 'Biceps', 'Barbell', 'BB / EZ Curl'),
  ('UPPER BODY — PULL', 'Biceps', 'Dumbbell', 'DB Curl / Hammer / Incline'),
  ('UPPER BODY — PULL', 'Biceps', 'Machine / Cable', 'Cable / Machine Curl'),
  ('UPPER BODY — PULL', 'Biceps', 'Band', 'Band Curl'),
  ('UPPER BODY — PULL', 'Biceps', 'Bodyweight', 'Chin-Up / Inverted Curl'),
  ('UPPER BODY — PULL', 'Biceps', 'Kettlebell', 'KB Curl'),
  ('UPPER BODY — PULL', 'Lateral Delt', 'Default', 'DB Lateral Raise'),
  ('UPPER BODY — PULL', 'Lateral Delt', 'Dumbbell', 'DB Lateral Raise'),
  ('UPPER BODY — PULL', 'Lateral Delt', 'Machine / Cable', 'Cable Lateral Raise'),
  ('UPPER BODY — PULL', 'Lateral Delt', 'Band', 'Band Lateral Raise'),
  ('UPPER BODY — PULL', 'Lateral Delt', 'Bodyweight', 'Wall-Lean Raise'),
  ('UPPER BODY — PULL', 'Lateral Delt', 'Kettlebell', 'KB Lateral Raise'),
  ('CORE & ROTATION', 'Anti-Extension', 'Default', 'Plank / Ab Wheel'),
  ('CORE & ROTATION', 'Anti-Extension', 'Barbell', 'BB Rollout'),
  ('CORE & ROTATION', 'Anti-Extension', 'Dumbbell', 'DB Plank Drag'),
  ('CORE & ROTATION', 'Anti-Extension', 'Machine / Cable', 'Cable Crunch'),
  ('CORE & ROTATION', 'Anti-Extension', 'Band', 'Band Dead-Bug'),
  ('CORE & ROTATION', 'Anti-Extension', 'Bodyweight', 'Plank · Hollow Hold · Leg Raise'),
  ('CORE & ROTATION', 'Anti-Extension', 'Kettlebell', 'KB Plank Pull-Through'),
  ('CORE & ROTATION', 'Anti-Rotation', 'Default', 'Pallof Press'),
  ('CORE & ROTATION', 'Anti-Rotation', 'Barbell', 'Landmine Press'),
  ('CORE & ROTATION', 'Anti-Rotation', 'Dumbbell', 'DB Renegade Row'),
  ('CORE & ROTATION', 'Anti-Rotation', 'Machine / Cable', 'Cable Pallof Press'),
  ('CORE & ROTATION', 'Anti-Rotation', 'Band', 'Band Pallof Press'),
  ('CORE & ROTATION', 'Anti-Rotation', 'Bodyweight', 'Bird-Dog · Side Plank'),
  ('CORE & ROTATION', 'Anti-Rotation', 'Kettlebell', 'KB Suitcase Carry'),
  ('CORE & ROTATION', 'Rotation / Power', 'Default', 'Med-Ball Rotational Throw'),
  ('CORE & ROTATION', 'Rotation / Power', 'Barbell', 'Landmine Rotation'),
  ('CORE & ROTATION', 'Rotation / Power', 'Dumbbell', 'DB Russian Twist'),
  ('CORE & ROTATION', 'Rotation / Power', 'Machine / Cable', 'Cable Woodchopper'),
  ('CORE & ROTATION', 'Rotation / Power', 'Band', 'Band Woodchopper / Chop-Lift'),
  ('CORE & ROTATION', 'Rotation / Power', 'Bodyweight', 'Standing Rotation (no load)'),
  ('CORE & ROTATION', 'Rotation / Power', 'Kettlebell', 'KB Halo / Around-World'),
  ('CORE & ROTATION', 'Anti-Lateral / Carry', 'Default', 'Suitcase Carry'),
  ('CORE & ROTATION', 'Anti-Lateral / Carry', 'Barbell', 'BB Rack Carry'),
  ('CORE & ROTATION', 'Anti-Lateral / Carry', 'Dumbbell', 'DB Farmer / Suitcase Carry'),
  ('CORE & ROTATION', 'Anti-Lateral / Carry', 'Machine / Cable', 'Cable Side-Bend'),
  ('CORE & ROTATION', 'Anti-Lateral / Carry', 'Band', 'Band Side-Bend'),
  ('CORE & ROTATION', 'Anti-Lateral / Carry', 'Bodyweight', 'Side Plank Hold'),
  ('CORE & ROTATION', 'Anti-Lateral / Carry', 'Kettlebell', 'KB Farmer / Waiter Carry'),
  ('EXPLOSIVE / POWER', 'Triple-Extension', 'Default', 'Power Clean'),
  ('EXPLOSIVE / POWER', 'Triple-Extension', 'Barbell', 'Power Clean / High Pull'),
  ('EXPLOSIVE / POWER', 'Triple-Extension', 'Dumbbell', 'DB Hang Clean / Snatch'),
  ('EXPLOSIVE / POWER', 'Triple-Extension', 'Band', 'Band Pull-Through (speed)'),
  ('EXPLOSIVE / POWER', 'Triple-Extension', 'Bodyweight', 'Squat / Tuck Jump'),
  ('EXPLOSIVE / POWER', 'Triple-Extension', 'Kettlebell', 'KB Swing / Clean / Snatch'),
  ('EXPLOSIVE / POWER', 'Jump / Plyo', 'Default', 'Box Jump'),
  ('EXPLOSIVE / POWER', 'Jump / Plyo', 'Dumbbell', 'DB Jump Squat (light)'),
  ('EXPLOSIVE / POWER', 'Jump / Plyo', 'Band', 'Band-Resisted Jump'),
  ('EXPLOSIVE / POWER', 'Jump / Plyo', 'Bodyweight', 'Box / Broad / Tuck Jump'),
  ('EXPLOSIVE / POWER', 'Jump / Plyo', 'Kettlebell', 'KB Swing (max effort)'),
  ('EXPLOSIVE / POWER', 'Throw / Slam', 'Default', 'Med-Ball Slam'),
  ('EXPLOSIVE / POWER', 'Throw / Slam', 'Dumbbell', 'DB Push Press (light, fast)'),
  ('EXPLOSIVE / POWER', 'Throw / Slam', 'Machine / Cable', 'Cable Overhead Slam'),
  ('EXPLOSIVE / POWER', 'Throw / Slam', 'Band', 'Band Overhead Throw'),
  ('EXPLOSIVE / POWER', 'Throw / Slam', 'Bodyweight', 'Clap Push-Up'),
  ('EXPLOSIVE / POWER', 'Throw / Slam', 'Kettlebell', 'KB Snatch'),
  ('EXPLOSIVE / POWER', 'Lateral Power', 'Default', 'Skater Bound'),
  ('EXPLOSIVE / POWER', 'Lateral Power', 'Dumbbell', 'DB Lateral Lunge (fast)'),
  ('EXPLOSIVE / POWER', 'Lateral Power', 'Band', 'Band Lateral Bound'),
  ('EXPLOSIVE / POWER', 'Lateral Power', 'Bodyweight', 'Skater Bound / Lateral Hop'),
  ('EXPLOSIVE / POWER', 'Lateral Power', 'Kettlebell', 'KB Lateral Swing'),
  ('CONDITIONING', 'Sprint / Intervals', 'Default', 'Bike / Row Intervals'),
  ('CONDITIONING', 'Sprint / Intervals', 'Machine / Cable', 'Assault Bike / Rower / Ski-Erg'),
  ('CONDITIONING', 'Sprint / Intervals', 'Band', 'Band-Resisted Sprint'),
  ('CONDITIONING', 'Sprint / Intervals', 'Bodyweight', 'Shuttle Run · Hill Sprint'),
  ('CONDITIONING', 'Sprint / Intervals', 'Kettlebell', 'KB Swing EMOM'),
  ('CONDITIONING', 'Steady-State (Zone 2)', 'Default', 'Incline Walk / Easy Bike'),
  ('CONDITIONING', 'Steady-State (Zone 2)', 'Machine / Cable', 'Treadmill / Bike / Elliptical'),
  ('CONDITIONING', 'Steady-State (Zone 2)', 'Bodyweight', 'Jog · Hike · Ruck'),
  ('CONDITIONING', 'Steady-State (Zone 2)', 'Kettlebell', 'KB Carry Walk'),
  ('CONDITIONING', 'Mixed / Finisher', 'Default', 'Sled Push'),
  ('CONDITIONING', 'Mixed / Finisher', 'Barbell', 'BB Complex'),
  ('CONDITIONING', 'Mixed / Finisher', 'Dumbbell', 'DB Complex'),
  ('CONDITIONING', 'Mixed / Finisher', 'Machine / Cable', 'Sled / Prowler / Battle Rope'),
  ('CONDITIONING', 'Mixed / Finisher', 'Band', 'Band Shuttle'),
  ('CONDITIONING', 'Mixed / Finisher', 'Bodyweight', 'Burpee · Jump Rope · Bear Crawl'),
  ('CONDITIONING', 'Mixed / Finisher', 'Kettlebell', 'KB Complex')
on conflict (category, pattern, equipment, name) do nothing;
